- ChangeLog.md
- scripts/make_emperor.py
It was pointed out that the error message printed when sample names didn't
match between coordinates and mapping file was unclear. So the message has
been rephrased.
> DOC: Improve error message

- doc/index.html
As of 39.x Chrome is 64-bit for the mac :beers: 
https://code.google.com/p/chromium/issues/detail?id=18323
Fixes #322
> DOC: Remove note about Chrome 32-bit

- doc/installation_index.html
The button in the documentation pointed to version 0.9.3 as the "stable" 
version, I've changed the link to point to the releases page in GitHub, which
should always list the latest release at the top.
> DOC: Update link pointing to version 0.9.3

- CONTRIBUTING.md
- doc/README.md
This file is heavily based in scikit-bio's `CONTRIBUTING.md` file, though 
there's been a few major modifications to accommodate the differences between
the projects. I've also added `doc/README.md` with some information on how to
build the documentation (also heavily based on scikit-bio's `doc/README.md`).
Fixes #346
> DOC: Add CONTRIBUTING.md file to the repo

- ChangeLog.md
- emperor/support_files/js/animate.js
- tests/javascript_tests/test_animate.js
The framework would try to animate trajectories with a single unique 
timepoint, even though it makes no sense and those should be ignored as they
are not very relevant in the context of an animation.
I've added a new test case to check for this.
> BUG: Fix bug with animations

- ChangeLog.md
- README.md
- doc/index.html
- doc/installation_index.html
- emperor/core.py
We no longer have ownership of emperor.colorado.edu so all resources
should point to emperor.microbio.me.
Fixes #382
I've also updated the script that powers @emperor-helper:
https://github.com/ElDeveloper/worker/commit/bd5ea9d294b16520356154b1674513abc6e1a0b4
> DOC/MAINT: URLs now point to emperor.microbio.me

- emperor/support_files/js/draw.js
- emperor/support_files/js/model.js
- emperor/support_files/js/sceneplotview3d.js
- examples/build.py
- tests/javascript_tests/test_decomposition_model.js
- tests/javascript_tests/test_draw.js
- tests/javascript_tests/test_sceneplotview3d.js
This PR adds the axis lines to the `ScenePlotView3D` object, along with the necessary tests and updates to the decomposition model object.
The strategy here is to get the ranges over each dimension in every decomposition model object, then get all the decomposition model objects in a scene plot view, and union their ranges to get the final range.
-------
I had initially planned to submit a PR for the AxesViewController class, but I think this PR is already big as it is and we might get lost in the details. Also I'm not adding the percentage explained to the plot yet. :fork_and_knife:
> Add axis lines to ScenePlotView3D

- emperor/support_files/js/draw.js
- emperor/support_files/js/sceneplotview3d.js
- examples/template.html
- tests/javascript_tests/test_draw.js
- tests/javascript_tests/test_sceneplotview3d.js
This PR adds the necessary methods to add and remove the axes labels.
I noticed we could abstract out a few patterns so I made a couple helper methods for the add and remove methods. I also noticed we had a problem in the template.html file with a missing dependency declaration.
> Add percentage explained labels

- examples/template.html
This callback was never being executed because `$` is not defined and it
was in fact showing an error in the JavaScript console. Removing this
tag altogether does not seem to affect the behavior of the plot at all.
> BUG: Remove incorrect callback declaration

- emperor/core.py
- tests/test_core.py
As discussed in #454 and in #458, remote now accepts a custom URL instead of
just a boolean.
> ENH: Change remote to accept a custom URL

- emperor/support_files/js/controller.js
- emperor/support_files/js/sceneplotview3d.js
Since we were using an identifier-based way to retrieve the object, we
couldn't have more than one Emperor plot in a jupyter notebook. I've
changed the references to no longer use the id attribute.
> BUG: Allow multiple independent plots in 1 nb

- .travis.yml
- emperor/core.py
- emperor/parse.py
- emperor/qiime_backports/util.py
- emperor/support_files/templates/main-template.html
- scripts/make_emperor.py
- setup.py
- tests/_test_core_strings.py
- tests/test_core.py
- tests/test_parse.py
- tests/test_qiime_backports/test_util.py
Change the usage of OrdinationResults to match its new API.
Use scipy's procrustes function instead of scikit-bio's. This is the first of many steps towards PY3 compatibility.
> MAINT/ENH: Use scikit-bio>=0.4.0 and scipy>=0.17.0

- emperor/support_files/js/color-view-controller.js
- emperor/support_files/js/controller.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/shape-controller.js
- emperor/support_files/js/view-controller.js
- emperor/support_files/js/view.js
- emperor/support_files/js/visibility-controller.js
- tests/javascript_tests/test_color_view_controller.js
- tests/javascript_tests/test_sceneplotview3d.js
- tests/javascript_tests/test_shape_controller.js
- tests/javascript_tests/test_visibility_controller.js
This moves rendering to an event-based action, where new frames are only rendered when the views are changed in some way. previously it was rendering a new frame regardless of it was needed or not.
> Render only on changes

- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/view-controller.js
This adds the name of the sample clicked when you click it.
> Info div. Fixes #327

- emperor/support_files/js/draw.js
- emperor/support_files/js/sceneplotview3d.js
- tests/javascript_tests/test_draw.js
The size of the font in the axes labels is now determined according to
the range of the datapoints (like with the sphere sizes).
> ENH: Improve axes labels font size

- doc/source/emperor_objects.rst
- doc/source/index.rst
- emperor/__init__.py
- emperor/_pandas.py
- emperor/core.py
- emperor/pandas.py
- emperor/support_files/js/model.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/templates/logic-template.html
- setup.py
- tests/_test_core_strings.py
- tests/javascript_tests/test_decomposition_model.js
- tests/test_pandas.py
This PR adds a helper function, `scatterplot`, that can take as only argument a
Pandas DataFrame and returns an Emperor object. The function itself
extracts the numerical data from the DataFrame and creates a dummy
OrdinationResults object.
Note that this is a rather experimental feature, so testing/suggestions are
very welcome.
This PR depends on #516 so merge that PR first.
> ENH: Add support to plot 🐼s DataFrame objects

- emperor/support_files/js/sceneplotview3d.js
When editing text in the notebook and using the arrows to navigate, the
OrbitControl object would listen to those events and pan the plot around.
> BUG: Disable arrow keys from the OrbitControl object

- emperor/support_files/js/axes-controller.js
Turns out Jupyter sets some styling on the cells of the HTML tables,
with these few changes those settings are removed.
Additionally, the colorpicker for the background was being set as white
by default, this should also fix that problem.
> BUG: Fix styling problem in the Jupyter 📓

- emperor/support_files/js/axes-controller.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/view.js
- tests/javascript_tests/test_decomposition_view.js
In the current version of emperor, if you flip the orientation of one of the axis, you may end up in a situation where the range data lies outside of the current axes. To remediate this, the `dimensionRanges` properties are updated to reflect the new range that the data spans. Additionally, we need to keep track of when an axis is reoriented, so we know when change the ranges back in a situation when we are swapping out a *flipped* dimension.
I've also improved the test cases to reproduce the problem.
-------
This one took longer than I was hoping. 😫
> Flipping bug 🐞

- emperor/support_files/js/axes-controller.js
- emperor/support_files/js/view-controller.js
- tests/javascript_tests/test_view_controller.js
After starting the implementation of `AnimationsViewController`, I noticed that there would be a fair amount of repeated code between this new class, `AxesController` and `EmperorAttributeABC`, therefore I decided to move that redundant code to a new base class `EmperorViewController`.
This new class understands what a decomposition view dictionary is, but doesn't really alter the functionality that EmperorViewControllerABC provides. The tests and most of the code were extracted from `EmperorAttributeABC`.
> Surgically add the EmperorViewController class

- emperor/support_files/js/draw.js
- tests/javascript_tests/test_draw.js
THREE.Sprite objects can't properly be rendered when we use the
SVGRenderer, hence we add an extra attribute to the objects we return
from makeLabel. In this attribute text is stored, such that when
rendering we can check for its presence, and add the appropriate SVG
element.
> HACK: Add extra attribute to denote text

- emperor/support_files/js/abc-view-controller.js
- emperor/support_files/js/color-view-controller.js
- emperor/support_files/js/controller.js
- emperor/support_files/js/scale-view-controller.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/shape-controller.js
- emperor/support_files/js/view-controller.js
- emperor/support_files/js/visibility-controller.js
- tests/javascript_tests/index.html
- tests/javascript_tests/test_color_view_controller.js
- tests/javascript_tests/test_scale_view_controller.js
- tests/javascript_tests/test_shape_controller.js
- tests/javascript_tests/test_view_controller.js
- tests/javascript_tests/test_visibility_controller.js
When matrices with more than 1000 samples are loaded in emperor, none of the tabs are "active" (meaning that there is no table of colors, shapes, scales, etc) until a metadata category is selected for each of the controllers. After a metadata category is selected, the grid with the colors, shapes or scales is displayed, and the program should continue to work as usual.
Making these changes allows us to load the EMP (~30K samples) in about 7-10 seconds, the memory consumption is greatly reduced and the overall experience is smoother.
In making these changes, I had to make a few additional changes:
- Sort metadata headers alphabetically.
- Make the `setEnabled` method disable the widgets in the current view controller.
- Allow for `setMetadataField` to take `null` as a parameter, this in …
> PERF: Lazily load large studies to improve performance

- emperor/support_files/js/controller.js
The plot's context menu is now shown without the need of holding shift
and right-clicking. With this patch, the user will need to *only* right
click to show the context menu.
Fixes #563
> ENH: Remove the requirement to shift+right click

- emperor/support_files/js/axes-controller.js
- emperor/support_files/js/model.js
- emperor/support_files/js/sceneplotview3d.js
- tests/javascript_tests/test_decomposition_model.js
Label names are now fixed to account for scikit-bio's OrdinationResults IO
module. The UI for the axes names has now changed to allow users to click on
menus and checkboxes (like in the previous version of emperor) instead of
clicking on the scree plot.
The variation explained by each axis is now shown **only** for non-custom axes.
While the scree plot interaction was *fun*, I think it was a bit confusing, so
I think this is better.
Fixes #562
> BUG: Fix problem with axes labels

- emperor/__init__.py
- emperor/core.py
- emperor/util.py
- tests/test_core.py
- tests/test_pandas.py
- tests/test_util.py
Deals with a problem where plots created with the `remote=True` argument would lead to the plots failing if new dependencies were added.
The base URL is now resolved depending on the version string. I had to change the tests because we can no longer test `remote=True` explicitly as the version string will change dependent of the version.
@wasade, this would deal with the need to update the figures in the deblur-manuscript repo.
------------
> BUG: Resolve stable URLs depending on package version

- .travis.yml
- emperor/support_files/js/draw.js
- setup.py
Reported by @ebolyen, long axes labels would be clipped. To fix this
I've made the font canvas bigger, so that it can at least fit 25
characters, after which it will add `...` at the end of the label (this
logic was already in place but was not noticeable due to the bug).
I've also upped the JINJA2 version to at least be 2.9.
see https://github.com/qiime2/q2-emperor/issues/41
> BUG/BLD: Fix problem with labels being clipped

- emperor/support_files/js/axes-controller.js
- emperor/support_files/js/sceneplotview3d.js
- tests/javascript_tests/test_sceneplotview3d.js
The color slector for the axes labels and lines can now be set to empty
(or null), this results in the labels and lines to be hidden. This PR also
adds the appropriate tests.
See animated gif:
Fixes #248.
> ENH: Hide axes labels and lines

- emperor/support_files/js/controller.js
- emperor/support_files/js/view.js
- tests/javascript_tests/test_decomposition_view.js
Just like in the previous version of emperor, though this time the banner's color is aware of the scene's background color to update accordingly.
For example:
> Adds a banner with number of visible elements

- emperor/support_files/js/sceneplotview3d.js
The controls only need to be updated if the rotation is enabled.
Merge #614 first, as it includes the version updates.
Fixes #605
> BUG: Fix bug where plot would rotate slightly

- emperor/support_files/js/animations-controller.js
- tests/javascript_tests/test_animations_controller.js
The grid displaying the colors for the traces was not updated after the
first change to the trajectory category. This has been fixed and I've
added a few missing tests.
> BUG: Fixes a bug in the animations colors

- emperor/support_files/js/controller.js
- emperor/support_files/js/sceneplotview3d.js
- tests/javascript_tests/test_sceneplotview3d.js
Users can now click or double-click to copy a sample's name. If clicking
on a sample, they'll need to also click on the banner at the bottom
left. If double clicking on a sample, the name is automatically copied
to the clipboard.
First clicking on a sample then on the legend to get the text. And another example double-clicking a sample to get the text.
> ENH: Copy sample names to clipboard.

- emperor/support_files/js/color-view-controller.js
- tests/javascript_tests/test_color_view_controller.js
Previously when a continuous colormap was set and the user downloaded
the SVG image, Emperor would produce a categorical list of the values,
this PR changes this so that a colormap is produced instead.
Fixes #336
> ENH:Download colormap instead of discrete legend

- emperor/support_files/js/model.js
- tests/javascript_tests/test_decomposition_model.js
Fixes a problem where metadata categories would appear to be ordered
randomly. Unique values are now sorted first alphabetically and then
numerically, mimicking the behaviour of the previous version of Emperor.
Fixes #618
> BUG: Sort unique metadata categories

- emperor/core.py
- tests/test_core.py
Two cases are now explicitly checked for:
1) None of the samples in the ordination are part of the metadata.
2) Some samples in the coordinates matrix are not part of the metadata.
In this case the error can be overridden with the ingore_missing_samples
argument.
> ENH: Add exceptions and tests for missing samples

- emperor/support_files/js/axes-controller.js
- emperor/support_files/js/controller.js
This PR adds a button to download an SVG file of the scree plot.
This also includes a few lines that were missing from #638 (I accidentally left them out 😱 ... see controller.js).
Fixes #599
> ENH: Add download scree plot button

- emperor/support_files/js/controller.js
Resizing the menu would erroneously be triggered by double-clicking the
menu, whereas it should only be triggered when double-clicking the
resize handle.
This had previously been reported by @wasade and a few others.
> BUG: Fix problem with double-click resize

- emperor/core.py
- tests/test_core.py
The setting setter was not taking into consideration the opacity and the
animations types.
Fixes #650
> BUG:Add missing attribute types in settings setter

- emperor/support_files/js/draw.js
- emperor/support_files/js/sceneplotview3d.js
- tests/javascript_tests/runner.js
This patch increases the labels' size by dynamically calculating the
dimensions of the canvas depending on the font and the width of the
text.
Fixes #598
As a comparison:
> ENH: Increase text size

- emperor/support_files/js/controller.js
This patch adds a message (in the sample counter) stating that hiding
samples in an ordination can be misleading.
Fixes #589 
Example animated gif:
> ENH: Warn users when hiding samples from a plot

- emperor/support_files/js/axes-controller.js
- emperor/support_files/js/controller.js
This should improve the discoverability of the context menu, HT to @wasade for pointing this out. Right clicking continues to work, just in case.
Example as a standalone plot:
Example as a plot in the Jupyter notebook:
While putting this together, I noticed a couple of oddities in styling of the axes-controller.js file, hence those unrelated changes.
> ENH: Add button to show context menu

- emperor/support_files/js/axes-controller.js
- emperor/support_files/js/color-editor.js
The text inputs in the color picker propagated the keypress and keydown
events all the way down to the notebook. In the case where the inputs
conflicted with a shortcut in the notebook, the shortcut itself would be
triggered.
This has been fixed by preventing the propagation of events in all the
color pickers.
Thanks to @JWDebelius for reporting this bug. 👍
> BUG: Prevent input propagation in the notebook 📓

- emperor/support_files/js/animations-controller.js
According to the documentation[1], the UI has to be manually refreshed
after changes to a button's state.
[1] - http://api.jqueryui.com/button/ see the refresh() section
> BUG: Refresh button state

- emperor/support_files/js/draw.js
- emperor/support_files/js/view.js
- emperor/support_files/js/visibility-controller.js
- tests/javascript_tests/test_decomposition_view.js
For procrustes plots edges were not being hidden when samples in it were. Demo:
Fixes #193
> BUG: Hide edges when hiding visible samples

- emperor/support_files/js/draw.js
- tests/javascript_tests/test_draw.js
The font sizes would become too small when the text was long and really big when the text was small. I've put in a few scaling factors to make the fonts look good in both cases, and have the "baseline" case be the string `Axis 1 (XX.XX %)`. 
For long text the font is too small (see the `DaysSinceExperimentStart` label on the first axis).
For short text the font is too large (see the `ab` label on the first axis).
For both cases the font looks *good* now:
-----------
> BUG: Fix problem with label sizes

- emperor/core.py
- emperor/support_files/js/draw.js
- Improve raycasting for arrows. Previously it would also check for
intersects with lines, which would lead to incorrect matches.
- Fix biplot coordinates computation so that it doesn't modify the
original array, instead it creates a copy. Prevents us from modifying
the inputed OrdinationResults object.
> ENH: Minor improvements to biplots UI

- doc/index.html
- emperor/core.py
Adds missing documentation for the feature_mapping_file parameter and re-organizes the main documentation page. We now directly point to nbviewer with all the example notebooks. See the screencapture below (the Notebooks tab points to this [link](https://nbviewer.jupyter.org/github/biocore/emperor/tree/new-api/examples/)).
> Re-organize documentation

- emperor/support_files/templates/logic-template.html
- tests/_test_core_strings.py
Fixes a problem where Jupyter's require declarations would shadow
Emperor's. Specifically while using the newest version of the Jupyter
notebook jquery would be updated to version 3.x and that version is not
compatible with several dependencies of Emperor.
For now this fix ensures that there will be no version conflicts by
putting all our dependencies under their own context.
----------
In case someone runs into this problem, here's how the UI would look (notice the dropdown menus are not loaded properly and no categories are visible):
> BUG: Fix version conflicts with Jupyter deps

- emperor/support_files/js/color-view-controller.js
There was a typo in the name of the colormap that prevented the data
from being colored correctly.
> BUG: Fix a bug with the red-yellow-blue colormap

- emperor/support_files/js/controller.js
- emperor/support_files/js/sceneplotview3d.js
- tests/javascript_tests/test_sceneplotview3d.js
Fixes #696 
The problem was that the camera assumed all coordinate spaces were centered around the origin. This assumption is not always true and it is **almost always** not true for weighted UniFrac (hence the panning of the camera in the screenshot in #696). While fixing this, I noticed that the target of the camera had an offset making plots rotate in an awkward way, this was fixed by adding calculating the target.
I also noticed that "re-centering" wasn't working properly either, re-centering the camera would lead to "almost" centered scenes. This last problem was fixed by disabling inertia/damping in the scene's controls.
> Fixes problem with the camera not being centered

- emperor/core.py
- emperor/support_files/js/animations-controller.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/view.js
- tests/javascript_tests/test_decomposition_view.js
- tests/javascript_tests/test_sceneplotview3d.js
- tests/test_core.py
If the plot was initialized with two dimensions, the UI would fail to
instantiate as several objects had the dimensions hard-coded. I've
changed this to make it dependant on the data. In addition the Python
API will now check for one-dimensional data.
Fixes #686
Fixes #705
> BUG: Fix problem with two-dimensional data

- emperor/support_files/js/axes-controller.js
- tests/javascript_tests/test_axes_controller.js
An axis would only be inverted if the loaded setting was "True", however
this would not honor the inversions that needed to happen if an axis was
currently set to True but should be changing to False.
I've included a unit test for this bug.
Fixes #717
> BUG: Fix bug with axis inversion in settings

- emperor/support_files/js/animate.js
- emperor/support_files/js/animations-controller.js
- emperor/support_files/js/draw.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/trajectory.js
- emperor/support_files/js/view.js
- tests/javascript_tests/test_decomposition_view.js
- tests/javascript_tests/test_trajectory.js
I split the Tube rendering into static and dynamic portions.  Static tubes are computed once upon starting playback.  Dynamic tubes are recalculated each frame.  Static tube draw range is recalculated each frame as well.  The effect is that we draw all the animation up to a certain point, then fit a single interpolated segment onto the end of it.  This is much faster than recomputing all the tubes every frame.  
Smooth on 20000 points on my laptop.  Should check it on more hardware since it touches the webGL layer.
> Fast Animation

- emperor/core.py
- tests/test_core.py
Allows for feature metadata to not include some of the features
represented in the ordination. The errors and warnings have been updated
to properly refer to either features or samples. I've added a couple of
tests to validate the error/warning messages.
Fixes #730  and #733
> ENH:Allow for missing features in feature metadata

- emperor/support_files/js/sceneplotview3d.js
This bug was introduced when we resolved the conflicts after merging #727 and #728. Namely `intersect` was stored as global variable, the name match was used instead of marker, and the mesh objects were accessing non-existent properties.
@dhakim87 if you can have a look and merge that would be great!
> Fix raycasting issue

- .travis.yml
- emperor/support_files/js/color-view-controller.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/ui-state.js
- emperor/support_files/js/view.js
- emperor/support_files/templates/logic-template.html
- setup.py
- tests/_test_core_strings.py
- tests/javascript_tests/index.html
- tests/javascript_tests/test_color_view_controller.js
- tests/javascript_tests/test_decomposition_view.js
- tests/javascript_tests/test_sceneplotview3d.js
:snake: 🔥 
We need to continue to use gjslint which only runs in 2.7.x (hence the invocation in .travis.yml) but otherwise we should be good.
> BLD: Drop support for Python 2.7

- emperor/support_files/js/controller.js
The code was using the old way to access grid data. I looked in the rest
of the codebase and there checked there aren't any other usages of
getData (only when necessary).
Fixes #754
> BUG: Fixes bug creating SVG legend

- ChangeLog.md
- doc/Makefile
- doc/source/index.rst
- doc/source/js_integration.rst
- emperor/support_files/js/abc-view-controller.js
- emperor/support_files/js/controller.js
- emperor/support_files/js/view-controller.js
- emperor/support_files/templates/logic-template.html
- tests/_test_core_strings.py
This is useful for the ongoing integration effort with Empress. In a conversation with @antgonza he suggested it would be useful to receive callbacks to the users double-clicking a category in Emperor. I implemented this using SlickGrid's events and THREE's event dispatcher objects.
Documentation looks like this:
> Adds callbacks to all controllers and documentation on how to use them

- emperor/support_files/js/sceneplotview3d.js
Some defaults changed in the most recent version of THREE.js. These were
preventing panning around with scatter plots. I also cleaned up some
additional code.
Fixes #770
> BUG: Update controller properties

- ChangeLog.md
- emperor/support_files/js/draw.js
- emperor/support_files/js/sceneplotview3d.js
- emperor/support_files/js/view.js
- emperor/support_files/templates/logic-template.html
- tests/_test_core_strings.py
- tests/javascript_tests/test_decomposition_view.js
- tests/javascript_tests/test_draw.js
- tests/javascript_tests/test_sceneplotview3d.js
- When a user visualized biplots, they wouldn't be able to swtich to parallel plot mode without some markers being left behind. This needed a bit of refactoring of some underlying methods #747.
- Expand the selection API to return the view object (this is for better integration with Empress) - #771 .
> Fixes an issue with parallel plots and augments the select API

- emperor/_pandas.py
This function will currently break due to changes in the skbio API -- OrdinationResults expects a pandas series as input for the eigvals object.
> Fixing scatterplot

- doc/source/js_integration.rst
- emperor/core.py
- emperor/support_files/templates/base-dependencies.html
- emperor/support_files/templates/html-container-template.html
- emperor/support_files/templates/jupyter-template.html
- emperor/support_files/templates/logic-template.html
- emperor/support_files/templates/standalone-template.html
- tests/_test_core_strings.py
- tests/test_core.py
Adding 4 new methods that will make integration with Empress much more straightforward. Before we were stripping the formatted HTML based on line numbers. Now CSS, HTML and JS blocks can be individually rendered via dedicated methods. In addition, custom code can be added via the `js_on_ready` attribute.
I updated the documentation to reflect these changes.
Fixes #777
> Add new methods to render individual Emperor components

- ChangeLog.md
- emperor/core.py
- emperor/support_files/templates/style-template.html
- emperor/util.py
- tests/_test_core_strings.py
- tests/test_util.py
- We use jsdelivr instead of rawgit which has better support for
versioning, etc.
- The style template needed jQuery but some distributions, such as Voilá,
would not make jQuery available making this template crash.
Fixes #751
> BUG: Remove rawgit and a bit of jQuery

- ChangeLog.md
- emperor/support_files/js/visibility-controller.js
- tests/javascript_tests/test_visibility_controller.js
Fairly small change that adds a button to toggle visibility. We used to have this in the previous version of Emperor and this was requested during an EMP meeting a couple of months ago by @justinshaffer & @FranckLejzerowicz.
This should be helpful for dealing with biplot arrows.
> ENH: Add Toggle Visible button to Visibility tab

- .github/workflows/main.yml
- ChangeLog.md
- emperor/util.py
- tests/test_core.py
- tests/test_pandas.py
- tests/test_util.py
These changes should allow the GitHub "Emperor CI" workflow to succeed again. They remove Python 3.7 (now EOL) from the test matrix, apply a workaround to get PhantomJS to work on the newest `ubuntu-latest` runner, and update the Python unit tests to work with new versions of Pandas. They also fix the `notebook` dependency to `<7`, since Jupyter 7 uses an incompatible extension system based on Jupyter Lab's.
> Update Python unit tests for new version of Pandas and fix CI workflow
