biocore/emperor

.travis.yml, ChangeLog.md, emperor/format.py, emperor/util.py
.travis.yml has been updated to test for the latest available version of 
NumPy.
Fixes #330
=> BUG/ENH: Add support for numpy 1.9.x

emperor/util.py
Addresses the pet peeves of the python community.
=> FIX/ENH: Fixes pep8 warnings in the util.py module

emperor/support_files/js/emperor.js
If taxa aren't present, it won't attempt to display them.  Addresses https://github.com/biocore/emperor/issues/368
=> BUG: Fixed empty taxa problem

emperor/sort.py, tests/test_sort.py
=> PEP8 sort.py and test_sort.py

emperor/parse.py, tests/test_parse.py
=> flake8-ing parse

ChangeLog.md, emperor/support_files/js/emperor.js
This fixes this issue https://github.com/biocore/emperor/issues/373
=> BUG: Fixed biplot scaling issue

emperor/support_files/js/model.js, emperor/support_files/js/view.js
Stubs out the code for the Models and Views of the MVC pattern.
=> Dummy model

scripts/make_emperor.py
@wdwvt1 ran into this issue, and the error message was not clear enough to diagnose easily.
=> Improve error message for erroneous biplot_fp case

emperor/support_files/js/controller.js, emperor/support_files/js/view_controller.js, tests/javascript_tests/index.html, tests/javascript_tests/test_view_controller.js
Here is the tentative code for the abstract base classes - EmperorViewControllerABC and EmperorAttributeABC.
Now, I'm not exactly sure about how we want to proceed with implementing the ColorViewController.  Implementing the ColorViewController may change how we want to modify these abstract base classes.
=> WIP: Baseclass

emperor/support_files/js/animate.js, emperor/support_files/js/color-editor.js, emperor/support_files/js/color-view-controller.js, emperor/support_files/js/controller.js, emperor/support_files/js/draw.js, emperor/support_files/js/model.js, emperor/support_files/js/sceneplotview3d.js, emperor/support_files/js/trajectory.js, emperor/support_files/js/ui.js, emperor/support_files/js/util.js, emperor/support_files/js/view-controller.js, emperor/support_files/js/visibility-controller.js, tests/javascript_tests/test_animate.js, tests/javascript_tests/test_color_view_controller.js, tests/javascript_tests/test_decomposition_model.js, tests/javascript_tests/test_decomposition_view.js, tests/javascript_tests/test_draw.js, tests/javascript_tests/test_plottable.js, tests/javascript_tests/test_sceneplotview3d.js, tests/javascript_tests/test_trajectory.js, tests/javascript_tests/test_ui.js, tests/javascript_tests/test_util.js, tests/javascript_tests/test_view_controller.js, tests/javascript_tests/test_visibility_controller.js
After migrating to require.js, I left the indentation unchanged to make the review-ability of #436 more bearable. This PR is adding the missing two spaces to all the libraries and fixing a few docstrings to fit under 80 columns.
--------
I think reviewing using GitHub's "hide whitespace changes" feature, might be useful in this case, see [here](https://github.com/blog/967-github-secrets).
=> Fix require.js indentation

emperor/support_files/js/controller.js, emperor/support_files/js/view-controller.js, examples/template.html, tests/javascript_tests/test_view_controller.js
Fixes the scrollbar issues in #435
=> Scrollbars

emperor/support_files/js/controller.js
Allow users to initialize a controller with a webgl canvas, this is needed to instantiate the controller in the SAGE2 environment.
=> ENH: Change needed for SAGE2

emperor/support_files/js/controller.js, emperor/support_files/templates/main-template.html, tests/_test_core_strings.py
Adds the emperor logo back as the page loads.
=> Add splashscreen

emperor/support_files/js/view-controller.js
Updates view-controller.js to be gjslint and jsdoc compatible.
=> View controller docs

emperor/support_files/js/color-view-controller.js, emperor/support_files/js/view-controller.js
Requires #482 
Updates color-view-controller to be gjslint and jsdoc compliant.
=> Color view controller docs

emperor/support_files/js/controller.js
I've also renamed buildUI to _buildUI, because it shouldn't be a method
that's publicly used.
=> DOC/STY: Adds necessary jsdoc and fixes gjslint

.travis.yml, emperor/core.py, emperor/format.py, emperor/qiime_backports/biplots.py, emperor/qiime_backports/filter.py, emperor/qiime_backports/make_3d_plots.py, emperor/qiime_backports/parse.py, emperor/qiime_backports/util.py, emperor/util.py, scripts/make_emperor.py, setup.py, tests/_test_core_strings.py, tests/all_tests.py, tests/test_biplots.py, tests/test_core.py, tests/test_filter.py, tests/test_parse.py, tests/test_qiime_backports/test_biplots.py, tests/test_qiime_backports/test_filter.py, tests/test_qiime_backports/test_make_3d_plots.py, tests/test_qiime_backports/test_parse.py, tests/test_qiime_backports/test_util.py, tests/test_sort.py, tests/test_util.py
This is still a work in progress. The bulk of the work was done using 2to3 and there were a few hand-made changes, the commit history should describe these in detail.
This also includes a change to .travis.yml to run the PY3 tests.
Should fix #313
=> Add Python 3 compatibility

setup.py, tests/all_tests.py
Clean the output for all_tests.py and the descriptors for setup.py.
=> PY3K: Additional PY3 cleanup

emperor/support_files/js/controller.js, emperor/support_files/templates/logic-template.html, emperor/support_files/vendor/js/three.js-plugins/SVGRenderer.js, tests/_test_core_strings.py
=> generating SVG

emperor/_format_strings.py, emperor/support_files/css/emperor.css, emperor/support_files/js/emperor.js, tests/_test_core_strings.py, tests/_test_format_strings.py
Fixes a problem with the tables not showing properly (see #420). It additionally fixes other problems we've had with the sidebar. If all goes well, things should look just fine in Chrome/Safari/Firefox.
-------
Note this is a pull against master, not new-api.
=> Fixes styling problems

emperor/core.py, emperor/support_files/templates/logic-template.html, tests/test_core.py
These attributes modify the size of the plot when presented in a Jupyter
notebook.
=> ENH: Add attributes to change width and height

emperor/qiime_backports/util.py, tests/all_tests.py, tests/test_biplots.py, tests/test_parse.py
Solves the problem of other failing builds.
=> BLD: Fix failing travis builds

doc/index.html
Thanks @mortonjt for pointing this out.
=> DOC: Update dead link to gigascience

emperor/core.py, emperor/support_files/js/animations-controller.js, tests/javascript_tests/test_animations_controller.js, tests/test_core.py
This also adds the Python API, tests and the needed setters/getters.
=> Add color controls for animations controller

emperor/support_files/css/emperor.css, emperor/support_files/js/controller.js
An example of the functionality:
=> ENH: Add ability to resize plot space and menu

setup.py
Fixes #631, thanks to @ikirker for the report and the suggested patch.
=> BLD: Fix problem with setup.py and setuptools

tests/test_biplots.py
Should allow for the tests to pass as they are failing right now.
=> TST: Improve unit tests in biplots

doc/source/examples.rst
After chatting with @sjanssen2, I think this should clear up how to use this functionality. Any other suggestions are welcome 👍
=> DOC: Improve documentation for standalone plots

emperor/support_files/js/shapes.js, tests/javascript_tests/test_shape_controller.js
=> ENH: Add star geometry to shapes tab

emperor/support_files/css/emperor.css, emperor/support_files/js/controller.js
Makes tab names unselectable and adds thousands separators to the visibility count banner.
=> Minor UI improvements

.travis.yml
Should fix some broken builds (for other open PRs).
=> ENH: Tests other Python and NumPy versions

emperor/support_files/js/sceneplotview3d.js, emperor/support_files/js/view.js, setup.py
This PR explicitly removes objects that are not visible when raycasting.
=> Fix a problem where invisible or transparent objects would be intersected

emperor/support_files/js/sceneplotview3d.js, tests/javascript_tests/runner.js
Mostly takes the changes from @dhakim87 and fixes stylistic issues.
=> Fix _removeObjectsWithPrefix For Duplicate Object Names

ChangeLog.md, emperor/support_files/js/animate.js, emperor/support_files/js/animations-controller.js, emperor/support_files/js/view.js, tests/javascript_tests/test_animate.js, tests/javascript_tests/test_animations_controller.js, tests/javascript_tests/test_decomposition_view.js
This allows for synced empire plots.
=> ENH: Add events for the animations controller
